[workspace]
resolver = "2"
members = [
	#"azimuth",
	"display",
	"eclipse",
	"ipc",
	"manifold",
	"simular",
	"spatializer",
]

[workspace.dependencies]
serde = { version = "1.0.163", features = ["serde_derive"] }
tokio = { version = "1.32.0", features = [
	"macros",
	"rt-multi-thread",
	"sync",
	"time",
] }

[workspace.dependencies.gluon]
git = "https://github.com/Technobaboo/gluon"
branch = "refactor/strongipc"

[workspace.dependencies.stardust-xr-fusion]
git = "https://github.com/StardustXR/core.git"
branch = "refactor/strongipc"

[workspace.dependencies.stardust-xr-molecules]
git = "https://github.com/StardustXR/molecules.git"
branch = "refactor/strongipc"
