[workspace]
resolver = "2"
members = ["azimuth", "display", "eclipse", "ipc", "manifold", "simular"]

[workspace.dependencies]
serde = { version = "1.0.163", features = ["serde_derive"] }
tokio = { version = "1.32.0", features = [
	"macros",
	"rt-multi-thread",
	"sync",
	"time",
] }

[workspace.dependencies.gluon-ipc]
version = "0.1.1"
# git = "https://github.com/StardustXR/gluon-ipc.git"

[workspace.dependencies.stardust-xr-fusion]
version = "0.53.0-rc.1"
# git = "https://github.com/StardustXR/core.git"

[workspace.dependencies.stardust-xr-molecules]
version = "0.53.0-rc.1"
# git = "https://github.com/StardustXR/molecules.git"
